export const skillTaxonomyGroups = [
  {
    category: "Core Development",
    skills: [
      "Full-Stack Web Development",
      "Frontend Development",
      "Backend Development",
      "Web Development",
      "Mobile App Development",
      "Desktop App Development",
      "REST API Development",
      "Application Deployment",
    ],
  },
  {
    category: "Design",
    skills: [
      "UI/UX Design",
      "Graphic Design",
      "Figma",
      "Responsive Web Design",
      "Mobile-First Design",
    ],
  },
  {
    category: "Creative",
    skills: [
      "Video Editing",
      "Photography",
      "Product Photography",
      "Content Creation",
    ],
  },
  {
    category: "Marketing",
    skills: [
      "Digital Marketing",
      "Social Media Management",
      "Copywriting",
      "SEO",
    ],
  },
  {
    category: "Frontend Development",
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Vite",
      "Tailwind CSS",
      "Bootstrap",
      "Component-Based Architecture",
      "State Management",
      "Form Handling",
      "Client-Side Validation",
      "API Integration",
      "Authentication Flow",
      "Image Compression",
      "Search and Filtering",
      "Pagination",
      "Dashboard Development",
      "Admin Panel Development",
      "Web Performance Optimization",
      "Progressive Web Apps (PWA)",
    ],
  },
  {
    category: "Backend Development",
    skills: [
      "Node.js",
      "Express.js",
      "Laravel",
      "PHP",
      "Next.js Server Actions",
      "Next.js Route Handlers",
      "CRUD API",
      "Authentication",
      "Authorization",
      "JWT",
      "Session Authentication",
      "Role-Based Access Control",
      "Middleware",
      "File Upload",
      "File Management",
      "Email Integration",
      "Rate Limiting",
      "Database Transactions",
      "API Validation",
      "WebSocket",
      "Real-Time Applications",
      "Background Processing",
    ],
  },
  {
    category: "Database",
    skills: [
      "PostgreSQL",
      "MySQL",
      "MariaDB",
      "Supabase",
      "Prisma ORM",
      "Sequelize",
      "Database Schema Design",
      "Relational Databases",
      "Database Modeling",
      "Database Integration",
      "Database Migrations",
      "Database Seeding",
      "Database Relations",
      "Query Optimization",
      "Database Indexing",
      "Database Backup and Restore",
      "Local Data Storage",
    ],
  },
  {
    category: "DevOps & Infrastructure",
    skills: [
      "Vercel",
      "VPS Deployment",
      "Nginx",
      "Docker",
      "Docker Compose",
      "PM2",
      "Cloudflare",
      "Cloudflare Tunnel",
      "DNS Configuration",
      "Custom Domains",
      "SSL/TLS and HTTPS",
      "Environment Variables",
      "GitHub Deployment",
      "Basic Server Security",
      "Reverse Proxy",
      "Port Management",
    ],
  },
  {
    category: "Desktop Development",
    skills: [
      "Java",
      "Java Swing",
      "Java AWT",
      "Python",
      "Electron",
      "Desktop GUI Development",
      "Desktop Form Applications",
      "Desktop CRUD Applications",
      "Desktop File Handling",
      "Desktop Input Validation",
      "Desktop Event Handling",
      "Desktop Application Navigation",
      "Desktop Application Packaging",
      "Cross-Platform Desktop Development",
    ],
  },
  {
    category: "Mobile Development",
    skills: [
      "Flutter",
      "Dart",
      "Flutter UI Development",
      "Responsive Mobile UI",
      "Mobile App Navigation",
      "REST API Integration",
      "Local Storage",
      "Image Upload",
      "Mobile CRUD Applications",
      "Backend Integration",
      "Android Development",
      "Cross-Platform Mobile Development",
    ],
  },
  {
    category: "Software Engineering",
    skills: [
      "Object-Oriented Programming",
      "Functional Programming",
      "MVC Architecture",
      "Component Architecture",
      "Client-Server Architecture",
      "REST Architecture",
      "Application Architecture",
      "Clean Code",
      "Reusable Components",
      "Separation of Concerns",
      "Input Validation",
      "Error Handling",
      "Debugging",
      "Troubleshooting",
      "Error Analysis",
      "Refactoring",
      "Performance Optimization",
      "Security Awareness",
      "Authentication Security",
      "Environment Configuration",
    ],
  },
  {
    category: "Development Tools",
    skills: [
      "Git",
      "GitHub",
      "Git CLI",
      "Git Branching",
      "Commit Management",
      "Git Merge",
      "Merge Conflict Resolution",
      "Git Revert",
      "Git Reset",
      "Visual Studio Code",
      "Terminal",
      "PowerShell",
      "Bash",
      "npm",
      "Composer",
      "Prisma CLI",
      "Docker CLI",
      "Linux CLI",
      "SSH",
      "Postman",
      "Browser DevTools",
    ],
  },
  {
    category: "Integrations",
    skills: [
      "Google Maps API",
      "Spotify API",
      "SMTP",
      "Third-Party REST API Integration",
      "OAuth",
      "Webhooks",
      "Real-Time Services",
      "File Storage Services",
    ],
  },
  {
    category: "Operating Systems & Servers",
    skills: [
      "Windows",
      "Linux",
      "Fedora",
      "Arch Linux",
      "Ubuntu",
      "Ubuntu Server",
      "WSL",
      "Linux Server Administration",
      "VPS Management",
      "Package Management",
      "systemd",
      "Firewall Configuration",
      "Network Troubleshooting",
      "Port Troubleshooting",
      "Process Management",
      "Log Analysis",
      "Server Configuration",
    ],
  },
  {
    category: "Application Domains",
    skills: [
      "Company Profile Websites",
      "Portfolio Websites",
      "Landing Pages",
      "E-Commerce Applications",
      "Marketplace Applications",
      "Dashboard Applications",
      "Admin Panels",
      "Authentication Systems",
      "User Profile Systems",
      "Real-Time Chat",
      "Cloud Storage Applications",
      "Link Management Platforms",
      "Weather Applications",
      "Location-Based Applications",
      "Google Maps Applications",
      "Music Applications",
      "CRUD Applications",
      "Inventory Systems",
      "Simple ERP Systems",
      "File Management Systems",
      "Mobile Applications",
      "Internal Management Systems",
    ],
  },
] as const;

export const skillTaxonomy = skillTaxonomyGroups.flatMap(({ category, skills }) =>
  skills.map((name) => ({ name, category })),
);

const canonicalSkills = new Map(
  skillTaxonomy.map((skill) => [skill.name.toLocaleLowerCase("id-ID"), skill.name]),
);

export function getCanonicalSkillName(value: string) {
  const normalizedValue = value.trim().toLocaleLowerCase("id-ID");
  return canonicalSkills.get(normalizedValue) ?? skillAliases.get(normalizedValue);
}

const skillAliases = new Map<string, string>([
  ["react.js", "React"],
  ["react development", "React"],
  ["next.js development", "Next.js"],
  ["seo dasar", "SEO"],
  ["websocket dasar", "WebSocket"],
  ["state management dasar", "State Management"],
  ["postman dasar", "Postman"],
  ["oauth dasar", "OAuth"],
  ["webhook dasar", "Webhooks"],
]);
