import Link from "next/link";
import { updateProjectAction } from "@/app/actions/projects";
import PageHeader from "@/components/layout/PageHeader";
import { getProjectEditData } from "@/lib/my-jobs";

interface Props { params: Promise<{ projectId: string }> }
export default async function EditProjectPage({ params }: Props) {
  const { projectId } = await params; const data = await getProjectEditData(projectId);
  const required = new Set(data.project.skillsNeeded.filter((item) => item.required).map((item) => item.skillId));
  const optional = new Set(data.project.skillsNeeded.filter((item) => !item.required).map((item) => item.skillId));
  const deadline = data.project.deadline?.toISOString().slice(0, 10) ?? "";
  return <><PageHeader title="Edit Project" subtitle="Perubahan hanya diizinkan sebelum proposal pertama masuk." userName={data.ownerName} avatarUrl={data.ownerAvatarUrl} /><form action={updateProjectAction} className="space-y-5 rounded-xl border border-hairline bg-card p-6"><input type="hidden" name="projectId" value={data.project.id} /><label className="block text-sm font-bold">Judul<input name="title" defaultValue={data.project.title} minLength={5} maxLength={120} required className="mt-2 w-full rounded-lg border border-hairline bg-canvas px-4 py-3" /></label><label className="block text-sm font-bold">Deskripsi<textarea name="description" defaultValue={data.project.description} minLength={20} maxLength={3000} required rows={6} className="mt-2 w-full rounded-lg border border-hairline bg-canvas px-4 py-3" /></label><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Budget<input name="budgetRaw" type="number" defaultValue={data.project.budget ?? ""} min={50000} required className="mt-2 w-full rounded-lg border border-hairline bg-canvas px-4 py-3" /></label><label className="text-sm font-bold">Deadline<input name="deadline" type="date" defaultValue={deadline} required className="mt-2 w-full rounded-lg border border-hairline bg-canvas px-4 py-3" /></label><label className="text-sm font-bold">Mode Kerja<select name="workMode" defaultValue={data.project.workMode} className="mt-2 w-full rounded-lg border border-hairline bg-canvas px-4 py-3"><option value="REMOTE">Remote</option><option value="HYBRID">Hybrid</option><option value="ONSITE">Onsite</option></select></label></div><label className="block text-sm font-bold">Lokasi<input name="location" defaultValue={data.project.location ?? ""} maxLength={120} className="mt-2 w-full rounded-lg border border-hairline bg-canvas px-4 py-3" /></label><div className="grid gap-5 md:grid-cols-2"><fieldset><legend className="mb-2 text-sm font-bold">Skill Wajib</legend>{data.skills.map((skill) => <label key={skill.id} className="flex gap-2 py-1 text-sm"><input type="checkbox" name="requiredSkillIds" value={skill.id} defaultChecked={required.has(skill.id)} />{skill.name}</label>)}</fieldset><fieldset><legend className="mb-2 text-sm font-bold">Skill Opsional</legend>{data.skills.map((skill) => <label key={skill.id} className="flex gap-2 py-1 text-sm"><input type="checkbox" name="optionalSkillIds" value={skill.id} defaultChecked={optional.has(skill.id)} />{skill.name}</label>)}</fieldset></div><div className="flex justify-end gap-3"><Link href="/dashboard/lowongan-saya" className="rounded-full border border-hairline px-5 py-2.5 text-sm font-bold">Batal</Link><button type="submit" className="rounded-full bg-brand px-5 py-2.5 text-sm font-bold text-white">Simpan Perubahan</button></div></form></>;
}
